#!/bin/bash
echo "entrer votre note : "
read Note
if [ "$Note" -gt 20 ];then
echo "erreur"
elif [ "$Note" -ge 16 ];then
echo "tres bien "
elif [ "$Note" -ge 14 ];then
echo "bien"
elif [ "$Note" -ge 12 ];then
echo "assez bien "
elif [ "$Note" -ge 10 ];then
echo "moyen"
elif [ "$Note" -lt 10 ];then
echo "insuffisant"
elif [ "$Note" -lt 0 ];then
echo "erreur"
fi
